### ISSUE TITLE
Internal server error when cast Audio using Samsung tv

### ISSUE THREAD

**Issue by kun510** [ConnectSDK/Connect-SDK-Android-Core#155]
Hi,
I'm trying to cast a simple mp3 audio to Samsung DLNA, but I get this error many times:
Display Audio failure: Internal Server Error
Can anyone explain and fix this for me? Thanks

**Comment by theduc0x** [comment]
hi, I wonder if you have fixed that error yet? @kun510

**Comment by kun510** [comment]
@theduc0x I have fixed it

**Comment by theduc0x** [comment]
Can you show me how to fix it? @kun510

**Comment by kun510** [comment]
@theduc0x Please show the error or problem so I can look into it

**Comment by theduc0x** [comment]
During the process of connecting to a Samsung TV, the connection will run successfully and enter onDeviceReady

![image](https://github.com/user-attachments/assets/019cee5f-0e20-4315-8194-816674205bd9)

Then I used NanoHttp to create a server and wanted to transfer images to the TV 
And I can see that it has displayed images on the server "http://192.168.1.212:8888/"

However, when running this function, it will report an error "error when show image: com.connectsdk.service.command.ServiceCommandError: Internal Server Error"

![image](https://github.com/user-attachments/assets/c53439d6-02b3-4ff2-bcc3-cd66ee089ade)


@kun510 Do you have any way?

**Comment by kun510** [comment]
You run debug fun displayMedia in ConnectSDK DLNA Service, show String url, SubtitleInfo subtitle, String mimeType, String title, String description, String iconSrc, see if there are any errors, running on the server has nothing to do with DLNA Service @theduc0x

**Comment by theduc0x** [comment]
After a while of testing, I found that if it is an https url, it will be transmitted without error, but if it is http, the error will still be reported. @kun510
