### ISSUE TITLE
DLNA event subscription crashing application

### ISSUE THREAD

**Issue by se-bastiaan** [ConnectSDK/Connect-SDK-Android-Core#32]
My Sony Bravia television is (sometimes) detected as DLNA device, but not all the services have a subscription, so eventSubURL = null. If the DLNAService then runs `subscribeServices()`, it will iterate the complete list and it doesn't check for null values in the eventSubUrl field. Result: crash.

https://github.com/ConnectSDK/Connect-SDK-Android-Core/blob/1.4.3/src/com/connectsdk/service/DLNAService.java#L1058

![AndroidStudioDebug](https://cloud.githubusercontent.com/assets/1799914/6854063/252ee7c0-d3ef-11e4-8c6d-413afc287a97.png)

**Comment by frolov-alexey** [comment]
It was fixed here https://github.com/ConnectSDK/Connect-SDK-Android-Core/pull/33
